# Generated by Django 4.2.4 on 2023-08-24 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quoteapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="born_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
